version: "3"
services:
  database:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_DB=getren_api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  server:
    build: ./backend
    command: bash -c "flask db upgrade && flask run"
    restart: always
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - FLASK_APP=getren.py
      - FLASK_DEBUG=1
      - FLASK_DB_PORT=5432
      - FLASK_DB_HOST=database
      - FLASK_DB_NAME=getren_api
      - FLASK_DB_USER=user
      - FLASK_DB_PASSWORD=password
      - FLASK_MAIL_USERNAME=getren.xp@gmail.com
      - FLASK_MAIL_PASSWORD=alfredogoldxp
      - FLASK_MAIL_SENDER=getren.xp@gmail.com
      - GETREN_MAIL=getren.xp@gmail.com
    depends_on:
      - database
    ports:
      - 5000:5000

  client:
    build: ./client-getren
    restart: always
    stdin_open: true
    depends_on:
      - database
      - server
    ports:
      - 3000:3000
