version: "3"
services:
  database:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    build: ./server
    command: bash -c "flask db upgrade --directory database/migrations/ && flask run"
    restart: always
    tty: true
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./server:/app

  client:
    image: node:12.19.0
    command: npm start
    restart: always
    working_dir: /app
    stdin_open: true
    depends_on:
      - database
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

volumes:
  dbdata:
