version: "3"
services:
  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=getren_api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    build: ./backend
    command: flask run
    restart: always
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  client:
    image: node:12.19.0
    command: npm start
    restart: always
    working_dir: /app
    stdin_open: true
    depends_on:
      - database
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client-getren:/app

volumes:
  dbdata:
