version: "3"
services:
  database:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_DB=getren_api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    build: ./server
    command: bash -c "flask db upgrade --directory database/migrations && flask run"
    restart: always
    depends_on:
      - database
    ports:
      - 5000:5000

  client:
    build: ./client
    restart: always
    stdin_open: true
    depends_on:
      - database
      - server
    ports:
      - 3000:3000

volumes:
  dbdata:
