version: "3"
services:
  database:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_DB=getren_api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    build: ./server
    command: bash -c "flask db upgrade && flask run"
    restart: always
    tty: true
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - FLASK_APP=getren.py
      - FLASK_DEBUG=1
      - FLASK_DB_PORT=5432
      - FLASK_DB_HOST=database
      - FLASK_DB_NAME=getren_api
      - FLASK_DB_USER=user
      - FLASK_DB_PASSWORD=password
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./server:/app

  client:
    image: node:12.19.0
    command: npm start
    restart: always
    working_dir: /app
    stdin_open: true
    depends_on:
      - database
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

volumes:
  dbdata:
