"""empty message

Revision ID: 0efcf39222bf
Revises: 33384fb303f2
Create Date: 2020-11-22 20:29:41.310146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efcf39222bf'
down_revision = '33384fb303f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('course_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video') as batch_op:
        batch_op.drop_column('course_order')
    # ### end Alembic commands ###
