"""empty message

Revision ID: 33384fb303f2
Revises: f9dfe4b45fde
Create Date: 2020-11-21 19:38:02.045155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33384fb303f2'
down_revision = 'f9dfe4b45fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
