"""Criaçao da tabela curso

Revision ID: ead91eae32bb
Revises: 42dc349578aa
Create Date: 2020-10-26 22:30:24.791492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead91eae32bb'
down_revision = '42dc349578aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_curso', sa.String(length=128), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_data_criacao'), 'curso', ['data_criacao'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curso_data_criacao'), table_name='curso')
    op.drop_table('curso')
    # ### end Alembic commands ###
