"""empty message

Revision ID: f9dfe4b45fde
Revises: 9735afa8ae60
Create Date: 2020-11-09 13:52:10.832764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9dfe4b45fde'
down_revision = '9735afa8ae60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmation_token', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('password_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_token')
    op.drop_column('user', 'confirmation_token')
    # ### end Alembic commands ###
