name: Development CI

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Initialize containers
        run: |
          docker-compose up -d
          until curl localhost:5000 > /dev/null 2>&1 && curl localhost:3000 > /dev/null 2>&1; do \
            echo 'Containers ainda não inicializados'
            sleep 1
            echo 'Testando conexão com containers...'
          done
          echo 'Containers inicializados'

      - name: Run models tests
        run: |
          docker-compose exec -T server python3 test.py

      - name: Run postman tests
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{secrets.POSTMAN_KEY}}
          collection: postman_collection.json

      - name: Run cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
